name: Clone or Update Project on Remote Server

on:
  push:
    branches:
      - main

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Clone or Update Project on Server
        run: |
          sshpass -p "d9de659eeac2dfde" ssh -o StrictHostKeyChecking=no -p 7822 root@68.66.251.93 "
          if [ -d /newCi ]; then
              cd /newCi && git pull;
          else
              git clone https://github.com/mohamadTamimi123/pipHunterCiCd.git /newCi;
          fi
          "

      - name: Manage Docker Containers
        run: |
            sshpass -p "d9de659eeac2dfde" ssh -o StrictHostKeyChecking=no -p 7822 root@68.66.251.93 "
            docker stop \$(docker ps -a -q);
            docker rm \$(docker ps -a -q);
            cd /newCi && docker-compose up -d;
            "
      - name: Install NPM Packages
        run: |
          sshpass -p "d9de659eeac2dfde" ssh -o StrictHostKeyChecking=no -p 7822 root@68.66.251.93 "
            cd /newCi/backend/Express-app/ && npm install;
            "
