name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # مرحله 1: چک کردن کد از مخزن
      - name: Checkout code
        uses: actions/checkout@v2

      # مرحله 2: نصب Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      # مرحله 4: نصب sshpass
      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      # مرحله 5: ارسال پروژه به سرور
      - name: Clone or Update Project on Server
        run: |
          sshpass -p "%MWZJWkhS\$GW" ssh -o StrictHostKeyChecking=no -p 7822 root@68.66.251.93 "
          if [ -d /app/www ]; then
              cd /app/www && git pull;
          else
              git clone https://github.com/mohamadTamimi123/pipHunterCiCd.git /app/www;
          fi
          "

      # مرحله 6: اجرای docker-compose up
      - name: Manage Docker Containers
        run: |
          sshpass -p "%MWZJWkhS\$GW" ssh -o StrictHostKeyChecking=no -p 7822 root@68.66.251.93 "
          cd /app/www && docker-compose down;
          docker stop $(docker ps -aq) && docker rm $(docker ps -aq);
          docker-compose up -d;
          "
