name: Clone or Update Project on Remote Server

on:
  push:
    branches:
      - main

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Clone or Update Project on Server
        run: |
          sshpass -p "d9de659eeac2dfde" ssh -o StrictHostKeyChecking=no -p 7822 root@68.66.251.93 "
          if [ -d /newCi ]; then
              cd /newCi && git pull;
          else
              git clone https://github.com/mohamadTamimi123/pipHunterCiCd.git /newCi;
          fi
          "


      - name: Docker up
        run: |
          cd /newCi
          docker stop $(docker ps -a -q)
          docker rm $(docker ps -a -q)
          docker-compose up

