name: Deploy to Ubuntu Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: 68.66.251.93
          username: root
          password: d9de659eeac2dfde
          port : 7822
          script: |
            mkdir -p /var/www/html/cicd
            rsync -avz ./ /var/www/html/cicd/
            cd /var/www/html/cicd
            docker-compose down
            docker-compose up
            # sudo apt-get update && sudo apt-get install -y nodejs npm  (برای نصب nodejs و npm)
            # npm install  (برای نصب وابستگی های پروژه)
            # sudo systemctl restart nginx # یا هر سرویس دیگری که پروژه شما از آن استفاده می‌کند.
