name: Deploy to Ubuntu Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: 68.66.251.93
          username: root
          password: d9de659eeac2dfde
          port : 7822
          script: |
            cd /cicd/pipCiCD
            git reset --hard HEAD^
            git pull
            git fetch
            docker stop $(docker ps -a -q)
            docker rm $(docker ps -a -q)
            docker-compose up -d
            cd /backend/backend-app
            npm install
            npm run start:dev
           
